
target 'Messenger' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Messenger

# Firebase
pod 'FirebaseCore'
pod 'FirebaseAuth'
pod 'FirebaseStorage'
pod 'FirebaseFirestore'
    
# Others
pod 'MessageKit'
pod 'JGProgressHUD'
pod 'SDWebImage'


  target 'MessengerTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MessengerUITests' do
    # Pods for testing
  end

end
